name: build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get

      - name: Build Frontend
        run: make frontend

      - name: Build Backend
        run: make rly
