name: build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Build Frontend
        run: make frontend

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Get dependencies
        run: go get ./...

      - name: Build Backend
        run: make rly

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
