on:
  release:
    types: [published, prereleased]

name: Docker Image

jobs:
  publish:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build, tag, and push
      id: build-image
      env:
        HUB_USERNAME: nanmu42
        HUB_PASSWORD: ${{ github.token }}
        HUB_REPOSITORY: docker.pkg.github.com/nanmu42/orly/rly
        IMAGE_TAG: ${{ github.ref }}
      run: |
        docker login docker.pkg.github.com --username $HUB_USERNAME -p $HUB_PASSWORD
        docker build -t $HUB_REPOSITORY:$IMAGE_TAG .
        docker push $HUB_REPOSITORY:$IMAGE_TAG
