on:
  release:
    types: [published]

name: Docker Image

jobs:
  publish:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Find Tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Build, tag, and push
      id: build-image
      env:
        DOCKER_HUB_REPO: nanmu42/orly
        ALICLOUD_REPO: registry.cn-hongkong.aliyuncs.com/nanmu42/orly
        IMAGE_TAG: ${{ steps.vars.outputs.tag }}
      run: |
        docker login --username ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login --username ${{ secrets.ALICLOUD_USER }} -p ${{ secrets.ALICLOUD_PASSWORD }} registry.cn-hongkong.aliyuncs.com
        docker build -t $DOCKER_HUB_REPO:$IMAGE_TAG .
        docker tag $DOCKER_HUB_REPO:$IMAGE_TAG $ALICLOUD_REPO:$IMAGE_TAG
        docker push $DOCKER_HUB_REPO:$IMAGE_TAG
        docker push $ALICLOUD_REPO:$IMAGE_TAG
